### ISSUE TITLE
Bug in difference method

### ISSUE THREAD

**Issue by gktval** [NetTopologySuite/NetTopologySuite#141]
When I do the difference between two polygon geometries, the result will sometime have hanging ends; thus causing an invalid polygon and resulting in a CCW point direction when it should be CW.
The zip file below has two files, the original (Boundary.shp) and the result of a Union in which I do a difference. The half circle on the far left was should be in CW direction, but it is not.

[Boundary-Union.zip](https://github.com/NetTopologySuite/NetTopologySuite/files/643116/Boundary-Union.zip)

**Comment by FObermaier** [comment]
These are the input geometries:
![tmp4784](https://user-images.githubusercontent.com/2065346/36426539-906b18f6-164a-11e8-8776-c81d1debd9eb.png)
The result of the difference operation is either.
![tmp4785](https://user-images.githubusercontent.com/2065346/36426540-90890848-164a-11e8-9f1f-c5fddc697df1.png)
or
![tmp619d](https://user-images.githubusercontent.com/2065346/36426725-5826979e-164b-11e8-8812-4bf8cfd82782.png)


Unioning this will have no effect since the geometries are disjoint.
The ring orientationof all 4 result polygons is clockwise. If that is not what you need, call `Geometry.Reversed()`
