### ISSUE TITLE
TopologyException when generating a VoronoiDiagram

### ISSUE THREAD

**Issue by hallsbyra** [NetTopologySuite/NetTopologySuite#151]
To reproduce, use the following input  to VoronoiDiagramBuilder:

`POLYGON ((14.7119 201.6703, 74.2154 201.6703, 74.2154 166.6391, 14.7119 166.6391, 14.7119 201.6703))`

The error message:

>NetTopologySuite.Geometries.TopologyException: found non-noded intersection between LINESTRING(44.46365 107.13560000000001, 44.46365 -1707.7211500000005) and LINESTRING(44.463650000000058 -1707.7211500000005, -1847.4122000000002 184.15470000000002) [ (44.46365, -1707.7211500000005, NaN) ]

I realize this is a problem in the original Java code base, so I filed a [ticket](https://github.com/locationtech/jts/issues/74) there too.  Posting here in NTS in case anyone here can shed some light on the issue.

**Comment by Jmerk523** [comment]
This even happens with very simple rectangles:

`POLYGON ((10 10, 10 100, 40 100, 40 10, 10 10))`

Produces a similar error message:

`NetTopologySuite.Geometries.TopologyException: 'found non-noded intersection between LINESTRING(25.000000000000021 -80, 25 -2795.0399893361773) and LINESTRING(25.000000000000245 -2795.0399893361773, 22.272727272727273 -2792.2993868301783) [ (25, -2795.0399893361769, NaN) ]'`

**Comment by Jmerk523** [comment]
A workaround (correct me if I'm misusing something) seems to be to node the raw diagram and clip it yourself, rather than letting the `GetDiagram` method of `VoronoiDiagramBuilder` attempt the clipping on the invalid geometry:
`IGeometry input = ...`
`VoronoiDiagramBuilder voronoiBuilder = new VoronoiDiagramBuilder();`
`voronoiBuilder.SetSites(input.Coordinates);`
`var sub = voronoiBuilder.GetSubdivision();`
`var diagram = sub.GetVoronoiDiagram(GeometryFactory.Default); // this is the invalid geometry`
`var strings = SegmentStringUtil.ExtractNodedSegmentStrings(diagram);`
`var noder = new MCIndexNoder(new IntersectionAdder(new RobustLineIntersector()));`
`noder.ComputeNodes(strings);`
`var noded = SegmentStringUtil.ToGeometry(noder.GetNodedSubstrings(), GeometryFactory.Default);`
`var merger = new LineMerger();`
`merger.Add(noded);`
`var merged = GeometryFactory.Default.BuildGeometry(merger.GetMergedLineStrings());`

`merged` is now a fixed copy of the Voronoi diagram.
The benefit of the method above is that it preserves the geometry (compared to Buffer(0)) so that it can still be compared exactly to the input edges/sites (presumably the bad pieces are computed and so don't directly correspond exactly with any existing pieces).

**Comment by FObermaier** [comment]
Revisiting this issue reveals that it is no longer valid:
1. `POLYGON ((14.7119 201.6703, 74.2154 201.6703, 74.2154 166.6391, 14.7119 166.6391, 14.7119 201.6703))`
Using `VoronoiDiagramBuilder` with a `GeometryFactory` that uses the new `OverlayNG` functionality does not throw any exception.
2. `POLYGON ((10 10, 10 100, 40 100, 40 10, 10 10))`
Does not fail anymore.
