### ISSUE TITLE
Option to skip node validation check when doing operations like intersect?

### ISSUE THREAD

**Issue by henriksen** [NetTopologySuite/NetTopologySuite#165]
I'm doing a series of intersections between polygons and, frankly, it's taking way too long. So I did a bit of profiling and it turns out that `.Intersection()` is responsible for about half the time. But during `Intersection` there's a `CheckValid` call that alone is about a third of the total time. Now, the polygons I'm using are static and/or known beforehand to be valid. Is there a way to disable or skip validation? 

Would the rest of the `Intersection()` code still work if that step was skipped? If so, I could make a PR to add an overload to Intersection with a flag to skip validation.

![image](https://cloud.githubusercontent.com/assets/121837/25181071/913be8fe-2510-11e7-8a34-a50e07539d87.png)

**Comment by FObermaier** [comment]
Try setting `OverlayOp.NodingValidatorDisabled = true;`

**Comment by airbreather** [comment]
Be careful when doing what @FObermaier suggested: this may cause the `SnapIfNeededOverlayOp` to not fall back to a `SnapOverlayOp` in cases where it otherwise would, which means the resulting geometry might have very subtle problems with it that could have otherwise been corrected for you automatically.

**Comment by airbreather** [comment]
Can this be closed?

**Comment by henriksen** [comment]
Yes, the `NodingValidatorDisabled` seemed sufficient
