### ISSUE TITLE
NetTopologySuite extensions that are not part of JTS Topology Suite

### ISSUE THREAD

**Issue by FObermaier** [NetTopologySuite/NetTopologySuite#191]
Currently NetTopologySuite has some functionality that is not part of JTS TopologySuite
* All of `NetTopologySuite.Features`
  * Part of this belongs to [Geo|Topo]Json input/output
  * Part of this is feature handling
* All of `NetTopologySuite.CoordinateSystems`
* possibly more ...

I request that we consider moving them out to a seperate assembly or even seperate assemblies.

**Comment by DGuidi** [comment]
no objections from me, but what can be the actual value added?
I'd like a lot that NTS is coherent with JTS, but maybe this change isn't so useful

**Comment by xivk** [comment]
Let's make a list here of what needs to be moved:

- [ ] NetTopologySuite.Features
- [ ] NetTopologySuite.CoordinateSystems
- [ ] IO ShapeFiles https://github.com/NetTopologySuite/NetTopologySuite/issues/184
- [ ] IO GeoJson
- [ ] IO TopoJson

Any others?

**Comment by DGuidi** [comment]
TopoJSON is a proof of concept and I was unable to implement the "write" part. Maybe can be moved to a IO.Lab assembly, where other (current and future) experiments can be added

**Comment by xivk** [comment]
... or we move it to a seperate repo but don't release package yet.

**Comment by xivk** [comment]
- [ ] IO Postgis (what's the difference between 1 and 2?)
- [ ] IO MsSpatial
- [ ] IO Oracle (this may be in the JTS core, not sure)
- [ ] IO Spatiallite
- [ ] IO CloudStorage (?)
- [ ] IO GDB
- [ ] Windows.Forms
- [ ] Windows.Media
- [ ] Converter

(please remove/check those that shoudn't be moved)

**Comment by xivk** [comment]
Do we agree more or less on this list? I'll start creating the seperate repos then...

**Comment by xivk** [comment]
I moved a couple of the projects but I got stuck a bit at the GDB/ShapeFile projects because they are referencing each other. Will continue working on this later. Work is ongoing in a seperate branch:

https://github.com/NetTopologySuite/NetTopologySuite/tree/refactoring/remove-io-projects

**Comment by xivk** [comment]
Any feedback on this? A lot of work went into this. Can we merge in the branch to develop?

**Comment by FObermaier** [comment]
@xivk I'll take a look at it tonight.

**Comment by xivk** [comment]
Also, is the GML IO fully implemented and supported? And is that also part of JTS? What about KML? 

I tried to read a few GML files, they all fail but open fine in QGIS. I'm willing to do some work there because I need this feature but then I need to know, move to to another repo or improve the code here.

**Comment by FObermaier** [comment]
@xivk, is there a way that we can rely on just one `NetTopologySuite.Common.props` file. Especially the GeoAPIPackageVersion should be in sync.

**Comment by FObermaier** [comment]
Regarding GML. The functionality is in JTS core module so it should stay there.

**Comment by FObermaier** [comment]
It is just the geometry parsing/writing and it is GML 2.

**Comment by FObermaier** [comment]
@xivk, there is a [KMLWriter](https://github.com/NetTopologySuite/NetTopologySuite/blob/develop/NetTopologySuite/IO/KML/KMLWriter.cs) in the NTS (and JTS) core module. It only handles the geometry part.

**Comment by xivk** [comment]
Ok so KML & GML stay in, are they up to date with what's there in JTS?

As for `NetTopologySuite.Common.props`, that's a problem. Why does this always have to match up, usually it's no problem to replace an assembly, in Itinero that happens all the time, as long as you follow semver and don't introduce breaking changes.

If we really need to keep them in sync always then I would consider that an issue for everyone building packages with a dependency on GeoAPI and NTS because those would also require keeping this in sync. 

Anyway, there are some solutions sharing files in git I think or we host the file somewhere else. Or we take the GeoAPI version from whatever NTS version is installed.

**Comment by airbreather** [comment]
> If we really need to keep them in sync always then I would consider that an issue for everyone building packages with a dependency on GeoAPI and NTS because those would also require keeping this in sync.
>
> Anyway, there are some solutions sharing files in git I think or we host the file somewhere else. Or we take the GeoAPI version from whatever NTS version is installed.

Yeah I actually think the IO projects (mostly?) don't need to reference GeoAPI directly, but rather through NTS (I think I might have forgotten to check in #183 whether or not the direct references could be taken out... proper handling of indirect NuGet package references is one of the major features of the new project system).  So probably **instead of** `GeoAPIPackageReferenceVersion`, we should put `NetTopologySuitePackageReferenceVersion` in there and use that instead of an inline version for the `PackageReference` lines?  Assuming that we can't find a good solution to share (if we can, then the common props file would have both versions in it, no big deal).

Also a way to share it would be to put `NetTopologySuite.Common.props` in its own repo and include it as a submodule in all of the projects.  I'm not sure how much that would really help, because we would still have to remember to do a `git submodule foreach git pull origin develop` or something in every repo every time there's an update (unless we don't want the update to affect all repos, which would make things even more confusing).

An extreme might be a special `<Target>` that downloads the latest version of the file from the main repo's GitHub... this has a bunch of problems, though, because every time we update that file, we risk breaking all these other projects and not knowing about it until way later.

It's probably fine to just let these .props files start diverging, and maybe slimming each one down to just what's needed by the individual solution... it seems to come with the territory of taking on the added complexity of having so many different repos to maintain.

Looking at some of the .csproj files (this'll probably be most of them), `<SolutionDir>$(ProjectDir)..\..</SolutionDir>` is wrong.  There used to be that "NetTopologySuite.IO" subfolder in between them, but now there isn't, so I think this means they won't get signed.  I haven't tested any of this.

**Comment by airbreather** [comment]
In the original issue description, @FObermaier also called out `NetTopologySuite.Features` and `NetTopologySuite.CoordinateSystems`, are those still planned?

I don't personally have any stake in the matter, I just want to make sure we're not making those harder to move later by semi-ignoring them for now, especially `NetTopologySuite.Features`.

**Comment by FObermaier** [comment]
> It's probably fine to just let these .props files start diverging, and maybe slimming each one down to just what's needed by the individual solution... it seems to come with the territory of taking on the added complexity of having so many different repos to maintain.

OK, I'm fine with that.

**Comment by xivk** [comment]
I've had problems in the past with different packages referencing different GeoAPI versions via different packages and not being able to resolve this except for building my own locally. Could this be due to the signing of the assemblies (potentially opening up a can of worms here) or is that not the issue? If so, how can this be fixed? Perhaps only signing the stables?

Good question of @airbreather on `NetTopologySuite.Features` and `NetTopologySuite.CoordinateSystems`, but it still makes sense to separate out the IO packages. No need to wait for this to be done is what I mean.

I think things will become easier this way, we have the NTS core that is in sync with JTS, also the release cycles are in sync but now we won't have to follow that with the IO packages and we can improve them very fast (and there is quite a lot for work to be done on them). We also shouldn't release the IO packages as stable if they aren't feature complete or we should document what's supported and what's not. I'm willing to setup a documentation website similar to http://docs.itinero.tech/docs/index.html

**Comment by airbreather** [comment]
> I've had problems in the past with different packages referencing different GeoAPI versions via different packages and not being able to resolve this except for building my own locally. Could this be due to the signing of the assemblies (potentially opening up a can of worms here) or is that not the issue? If so, how can this be fixed?

I do recall having some problems like this, most recently NetTopologySuite/ProjNet4GeoAPI#21.  I touched on the reasons in [this comment](https://github.com/NetTopologySuite/ProjNet4GeoAPI/issues/21#issuecomment-351391508)... it can get complicated.

The problems I've seen have been caused by one of two things:
1. Assembly version (solution: use a binding redirect in an `App.config`)
2. There's an actual breaking change in GeoAPI, so **all** consumers need to reference the newer package.

> Perhaps only signing the stables?

Changing the public key token actually counts as 2. above, because a strong-named assembly has a different identity than one without a strong name (and so you can't just `bindingRedirect` the problem away).  I think we should still always sign all the assemblies... [this page](https://docs.microsoft.com/en-us/dotnet/framework/app-domains/strong-named-assemblies) explains the benefits to doing so.  I'm guessing that the actual reason why we sign our assemblies is so they can be used by applications that are also strong-named (strong-named assemblies can only reference other strong-named assemblies).

So if we only signed the stables, then that would essentially mean that such applications can only use the stable packages, which doesn't really seem right.

> I'm willing to setup a documentation website similar to http://docs.itinero.tech/docs/index.html

If it's all the same, I'd like to plug [GH Pages](https://pages.github.com) for this, since the docs could then just live in a separate branch of the repository and we get free hosting simply by turning on a setting in the repository.

**Comment by xivk** [comment]
Ok, so it *should* work when it's a non-breaking version upgrade, then that's fine for me. That's the behavior I expect. We don't really use SemVer at the moment but I guess that's impossible for NTS/GeoAPI but we should try to do this for the other packages.

About the docs, yes it would be easier on github but harder to auto-generate stuff like this: http://docs.itinero.tech/itinero/Itinero.RouterPoint.html Doesn't really matter for me, I just think we should also have some docs/samples once we release the next stable of NTS. We can continue this discussion in another issue later.

**Comment by xivk** [comment]
@FObermaier Can you comment on what to do with `NetTopologySuite.Features` and `NetTopologySuite.CoordinateSystems`?

**Comment by FObermaier** [comment]
@xivk, I have already moved out `NetTopologySuite.Features` to https://github.com/NetTopologySuite/NetTopologySuite.Features. It has not been removed from the main repository, though.

For the BSD3 license change, we need to move `NetTopologySuite.CoordinateSeqences`, too.
One part originally belongs to `NetToplogySuite.IO.GeoJSON` and one part is only for reprojecting `IGeometry`, `ICoordinateSequence`, `Coordinate` and `Envelope`. I think it can stay in the main repository, but should be used in a seperate project with a nuget package of its own. Afterall it is just a single file.

**Comment by FObermaier** [comment]
Having looked at it again I think we need to move
* `ICRSObject`
* `CRSBase`
* `CRSType`
* `LinkedCRS`
* `NamedCRS`
to `NetTopologySuite.Features` as `FeatureCollection` does have a direct reference to `ICRSObject`.

`NetTopologySuite.IO.GeoJSON` does need `NetTopologySuite.Features` and have the support for converting `ICRSObject` to and from JSON.

**Comment by airbreather** [comment]
> Do you think we should move NetTopologySuite.CoordinateSystems to a different repository, too? Would be cleaner.

This is one class; what's its purpose?  We have [`NetTopologySuite.Geometries.Utilities.GeometryEditor`](https://github.com/NetTopologySuite/NetTopologySuite/blob/4602f37ffb109d478b9094b2c401b8a7b2c5f5bc/NetTopologySuite/Geometries/Utilities/GeometryEditor.cs) that looks like it does everything in here.  If we're already going to break binary compatibility, then it doesn't seem like a stretch to just drop it entirely.

If we want something to let us edit geometries using `IMathTransform`, then couldn't we write an implementation of `IGeometryEditorOperation` that uses an instance of `IMathTransform` for the transformation and let the regular ol' `GeometryEditor` do the rest of the work?

**Comment by xivk** [comment]
Yes let's move the .CoordinateSystem stuff too.

The build is not setup yet for master, only develop. I can set this up right away if you want, the version # is parsed directly from the `SharedAssemblyVersion.cs`

**Comment by FObermaier** [comment]
@airbreather, dropping is fine with me, too. We can post the code in the wiki in case anyone really cares.
SharpMap uses the [same code in its own repository](https://github.com/SharpMap/SharpMap/blob/Branches/1.0/SharpMap/CoordinateSystems/Transformations/GeometryTransform.cs).

**Comment by FObermaier** [comment]
>The build is not setup yet for master, only develop. I can set this up right away if you want, the version # is parsed directly from the `SharedAssemblyVersion.cs`

That'd be great, I think I have set up NTS.Release on your itinero build server. I have not touched the parsing script (have I?) and the package feed needs to be checked. Could you do that? We should disable the NuGet push step until we know the output is what we want.

**Comment by xivk** [comment]
Ah I see now, the build is already looking good, nuget push is disabled. The only difference I can see with the develop build is vswhere (?)

**Comment by FObermaier** [comment]
> vswhere (?)

https://github.com/Microsoft/vswhere/

**Comment by xivk** [comment]
The build uses this script: https://github.com/NetTopologySuite/NetTopologySuite/blob/develop/build.bat

That means the build won't work until we merge into master.

**Comment by airbreather** [comment]
> The build uses this script: https://github.com/NetTopologySuite/NetTopologySuite/blob/develop/build.bat

I haven't really paid much attention to that script... some suggestions:
- we could distribute `vswhere` to do that comment
- if we add an explicit `/t:Restore;Build`, then it doesn't require an explicit out-of-band NuGet restore step beforehand like I'm assuming your build process is doing now (unless something's been fixed since the last time I was looking into command-line builds)
- if we add `/m`, then the build can use multiple CPU cores to hopefully finish faster

**Comment by xivk** [comment]
Sure, go ahead and edit in the develop branch, if it works there then it will also run on master... :+1:

**Comment by FObermaier** [comment]
Do we need to remove `-preXXXX` from the dependency definition to GeoAPI prior to pushing to the Release branch? If so, any idea how this can be handled automatically?

I have tried to play with https://docs.microsoft.com/en-us/nuget/reference/msbuild-targets#pack-target but have not come up with a working solution.

My idea was that we
* create an environment variable `Branch` on the build server. Its value is either `develop` or `master`
* add `/p:Branch=%Branch%` to the `build.bat`
* make `$(GeoAPIPackageReferenceVersion)` defined in `NetTopologySuite.Common.props` dependant on `$(Branch)`
* get this injected in the `*.nuspec` files (`/p:NuspecProperties:\"GeoAPIPackageReferenceVersion=...\"`).

**Comment by xivk** [comment]
@FObermaier I think we can do this manually for now no, then we can release. We can always try to get this automated for new releases.

I think if we merge to master and do the final touches there, then build and verify packages. If we keep track of what we did to get this done we create a checklist and try to automate as much of the process as possible for next time.

**Comment by airbreather** [comment]
Can someone please summarize what still remains to be done before this issue can be closed?

It also sounds like a separate issue should be opened to do whatever we need to do before turning automated NuGet pushes back on for the `develop` branch.

> My idea was that we
> 
> - create an environment variable `Branch` on the build server. Its value is either `develop` or `master`
> - add `/p:Branch=%Branch%` to the `build.bat`
> - make `$(GeoAPIPackageReferenceVersion)` defined in `NetTopologySuite.Common.props` dependant on `$(Branch)`
> - get this injected in the `*.nuspec` files (`/p:NuspecProperties:\"GeoAPIPackageReferenceVersion=...\"`).

I agree with @xivk that we should stick to doing this part manually for now, especially because #244 would likely change this workflow.
