### ISSUE TITLE
License change for JTS

### ISSUE THREAD

**Issue by FObermaier** [NetTopologySuite/NetTopologySuite#196]
With the release of JTS v1.15 it will be relicensed:
>JTS is dual-licensed under the Eclipse Public License 1.0 ("EPL") or the Eclipse Distribution License 1.0 (a Revised BSD-style license). More detail is provided in the LICENSES document.

I think we should/must follow that move. The issue is that we are having quite a few supporting projects (e.g. ShapeFile IO, GeoJson) that use code that was mainly/initially written by others or taken from different projects (e.g. GeoTools.NET)

For my part I have no problems relicensing the parts I did. We need to decide how to deal with this.

related:
* https://github.com/locationtech/jts/blob/4fe9af6e67c4bba7081e2a39c85407e558069852/FAQ-LICENSING.md
* https://github.com/locationtech/jts/blob/master/LICENSES.md
* https://github.com/locationtech/jts/issues/124

**Comment by DGuidi** [comment]
+1, absolutely
maybe we can separate code that cannot move to new licensing model to a different set of assemblies, with original license attached?

**Comment by airbreather** [comment]
I work for Urban Science, the company who developed Geotools.NET.  If you'd like, I can try to get you in contact with someone, though I can only promise to *try*.

I'm fine with my own contributions getting relicensed under a permissive license.

For what it's worth (I'm not a lawyer) I don't think NTS **needs** to relicense, and I especially don't think we need to block v1.15 over it.  EDL-1.0 is permissive, so we should be able to continue to bring in the EDL-1.0 licensed changes in JTS, port them to NTS, and then license the result under LGPL-2.1.

As far as I know, the only change we would **need** is to update the copyright notices we distribute with NTS.

The separate question is whether or not we would **want** to relicense.  Before JTS relicensed itself, our hands were somewhat tied: we could not distribute NTS under a permissive license, because it would have constituted a "derivative work" of a project that was licensed under the much more restrictive LGPL-2.1.  That's no longer the case, **but**, we would may need to make sure we get the permission of all* contributors.

*_I think I recall some organizations skipping over contributors who have only made [_de minimis_](https://en.wikipedia.org/wiki/De_minimis#Copyright) contributions, so that might make sense here too._

In any case, I really like the idea of relicensing NTS under a permissive license... MIT/Expat, BSD (2-clause or 3-clause), Apache 2.0, all of these would be fine with me.

**Comment by airbreather** [comment]
> maybe we can separate code that cannot move to new licensing model to a different set of assemblies, with original license attached?

I hope we don't have to do that.  We have [License.txt](https://github.com/NetTopologySuite/NetTopologySuite/blob/a7bb49dc4119ffef5592e2e45f8734acf32faa30/NetTopologySuite/License.txt), which should include the list of people we need to talk to (if it doesn't, then we need to fix that ASAP).

On that list, we can skip over the ones who have already distributed their work under permissive licenses unless we're trying to go BSD-0 or public domain or something.  That just leaves:

1. JTS should be good now, but I still want to do a bit of an audit to make sure that if there's anything that LocationTech cut out from JTS for its own legal reasons, we follow suit.
2. SharpMap, I don't know about.
3. Geotools.NET, I've offered to help address however I can.

**Comment by FObermaier** [comment]
> I work for Urban Science, the company who developed Geotools.NET. If you'd like, I can try to get you in contact with someone, though I can only promise to try.

@airbreather, it'd be great if this could be settled (to our consent) but I must admit that I'm not a lawyer either and when it comes to legalese my english is probably not that good. So I don't see myself in the position to negotiate with your employer if there are any issues to resolve.

So, how do we go about contacting former developers? Is dragging them into this discussion sufficient.
The input from [SharpMap](https://github.com/sharpmap/sharpmap) seems marginal, @DGuidi, what do you think.

>In any case, I really like the idea of relicensing NTS under a permissive license... MIT/Expat, BSD (2-clause or 3-clause), Apache 2.0, all of these would be fine with me.

Me to, but what is wrong with the license the JTS folks chose?

**Comment by airbreather** [comment]
> So, how do we go about contacting former developers? Is dragging them into this discussion sufficient.

I don't think so, since I think they assigned copyright to Urban Science for this (see the copyright notices that came with Geotools.NET itself).  This actually should make it easier for us if we want to do anything here, because I think it might be difficult to get a hold of some of those individuals.

>> In any case, I really like the idea of relicensing NTS under a permissive license... MIT/Expat, BSD (2-clause or 3-clause), Apache 2.0, all of these would be fine with me.
> 
> Me to, but what is wrong with the license the JTS folks chose?

EDL-1.0 is practically identical to BSD 3-Clause, with these changes:

1. `<YEAR>` turned into `(c) 2007`,
2. `<COPYRIGHT HOLDER>` turned into `Eclipse Foundation, Inc. and its licensors.`, and
3. `copyright holder` turned into `Eclipse Foundation, Inc.`

We're not the Eclipse Foundation, and we didn't start this in 2007, so if we wanted to use EDL-1.0, we'd wind up changing it back into the BSD 3-Clause anyway.

**Comment by DGuidi** [comment]
> The input from SharpMap seems marginal

marginal, or even none: maybe the reference in license.txt should be removed.
some code from dotspatial?

**Comment by FObermaier** [comment]
@DGuidi, AFAIK there is no DotSpatial code in the library. There is however code that supports conversion to and from DotSpatial geometries. This code is mine/ours and only dependant on the DotSpatial library.
It is only relvant for versions of DotSpatial up to v1.9. For v2.0 they chose to fork NTS and and adjust it to their needs.

@airbreather, ok then i think we should agree on relicensing to BSD3. We don't need a second license to allow possible LGPL derivative work as NTS already is a derivative work. Is that right?

I started a [wiki page](https://github.com/NetTopologySuite/NetTopologySuite/wiki/Contribution-from-other-projects) for code contribution from other projects. For what I can tell the only real issue is with the code from GeoTools.Net. Please feel free to add other "contributions" that you are aware of.

Other code/projects without explicit licenses:
* @jaundice, do you have any issues with a possible license change (`IStreamProvider`, possibly more)?
* @rstuven, do you have any issues with a possible license change (NetTopologySuite.IO.[PostGis|SqlServer2008|MsSqlSpatial], possibly more)?
* I think the (incomplete?) oracle stuff is mine, or yours @petlof?

**Comment by airbreather** [comment]
> We don't need a second license to allow possible LGPL derivative work as NTS already is a derivative work. Is that right?

I think the reason why Eclipse does the dual-licensing of EDL / EPL is because EDL is silent about patents, so someone downstream might choose to accept some additional restrictions imposed by the EPL in exchange for access to any patent claims that might be covered.  Compare these quick descriptions of [EPL](https://tldrlegal.com/license/eclipse-public-license-1.0-(epl-1.0)) and [BSD3](https://tldrlegal.com/license/bsd-3-clause-license-(revised)).

I'm honestly not sure which patents are in the Eclipse Foundation's patent pool that would make them choose to do this for JTS... anyway, unless NTS has patents of its own, I don't see a reason to dual-license NTS.

If we relicensed NTS under BSD3, then anyone downstream of NTS would still be able to license their own derivative work under LGPL, just like how NTS is allowed to be LGPL even though it's a derivative of the EPL-licensed JTS, because EPL / BSD3 doesn't impose any terms that are incompatible with LGPL.

> For what I can tell the only real issue is with the code from GeoTools.Net.

I think some of Geotools.NET also made its way into Proj.Net, which itself had some of its pieces make it back into GeoAPI.

**Comment by pauldendulk** [comment]
This is perhaps relevant to this discussion. A list of contributor to the NetTopologySuite git repo.

git shortlog --summary --numbered

   471	FObermaier
   468	DGuidi
   121	Diego Guidi
    96	Felix Obermaier
    25	rstuven
    21	Joe Amenta
    19	john.diss
    10	Ben Abelshausen
     8	John Diss
     6	codekaizen
     6	xivk
     5	Atle Frenvik Sveen
     4	Peter Löfås
     4	jackson.todd.a
     3	peter.lofas
     2	Kelly
     2	Peet Whittaker
     2	lloydstockman
     1	Asger Skovbo Petersen
     1	Brad Hards
     1	Making GitHub Delicious.
     1	T.M
     1	The Gitter Badger
     1	airbreather
     1	denniswelu
     1	jandic
     1	no_author

**Comment by FObermaier** [comment]
> I think some of Geotools.NET also made its way into Proj.Net, which itself had some of its pieces make it back into GeoAPI.

The reprojection code inside `GeoAPI` can be easily factored out into say `GeoAPI.Projections`. This would be in scope with #191 and [GeoAPI #30](https://github.com/NetTopologySuite/GeoAPI/issues/30)

**Comment by rstuven** [comment]
> @rstuven, do you have any issues with a possible license change (NetTopologySuite.IO.[PostGis|SqlServer2008|MsSqlSpatial], possibly more)?

No, I don't.

(Sorry for the delay 😅)

**Comment by airbreather** [comment]
What do you think about adding a GitHub "Project" for this and adding in separate issues for the separate activities that we need to do to make this happen?

**Comment by FObermaier** [comment]
This is a good idea.
