### ISSUE TITLE
Support for GeoPackage?

### ISSUE THREAD

**Issue by jpsgamboa** [NetTopologySuite/NetTopologySuite#217]
Are there any plans to support reading and writing to GeoPackage (http://www.geopackage.org/)?

**Comment by FObermaier** [comment]
[SharpMap](https://github.com/SharpMap/SharpMap) has GeoPackage support:
https://github.com/SharpMap/SharpMap/blob/Branches/1.0/SharpMap.Data.Providers.GeoPackage as it uses GeoAPI and NTS under the hood you should be able to reuse it.

One could consider to put the Geometry IO into a NetTopologySuite.IO project

**Comment by DGuidi** [comment]
can someone take a look at this? https://github.com/DGuidi/NetTopologySuite.IO.SpatiaLite/commit/96a2fc82af103427537601b98b612fc8e9a2877d

**Comment by airbreather** [comment]
> can someone take a look at this? https://github.com/DGuidi/NetTopologySuite.IO.SpatiaLite
>
> added code to spatialite project but maybe I can create a separate project for this.

Looks fine overall, thanks for getting it started!  I just have one small note and then responses to that last bit.

Can we use `PackageReference` for [mod_spatialite](https://www.nuget.org/packages/mod_spatialite) for the tests instead of copying it all into our own project?  Not sure how that would work, just asking.

From a brief read of what SpatiaLite and GeoPackage are, I think that a separate NuGet package might make more sense than making everyone have to see all of both "GaiaGeo*" and "GeoPackageGeo*" when they probably only use one format or the other.  Plus, pulling in a package with "SpatiaLite" in its name, when they know that they need the GeoPackage format, seems a bit weird.

That said, I'm not 100% sure.  Maybe 2.0 can take a breaking change to rename the package to be more generic like NetTopologySuite.IO.Sqlite and then that fixes everything?

Even if we distribute them in separate packages, I think it makes a lot of sense to keep them in the same GitHub project since both are clearly very much related.

**Comment by DGuidi** [comment]
I'll try to take a look at packagereference stuff but this test code is only for validation purposes (to be sure that external created geometries can be read with nts and vice versa); additionally I think can works only in [windows 10](https://github.com/sqlitebrowser/sqlitebrowser/wiki/SpatiaLite-on-Windows)
Probably this test code can be removed completely.

**Comment by DGuidi** [comment]
added latest stuff, except packagereference: hope to fix also this soon

**Comment by DGuidi** [comment]
@FObermaier @airbreather I need help for this, https://github.com/DGuidi/NetTopologySuite.IO.SpatiaLite/commit/3a7e75e79cc817ad938a2a86a4c29d07a60cc3da (see comments on failing tests)

Thanks for any kind of support.

**Comment by bricelam** [comment]
Correct, the `mod_spatialite` NuGet package currently only works for Windows. To get additional coverage, we (the EF team) just run these on our CI:

``` sh
# macOS
brew install libspatialite

# Ubuntu
sudo apt-get install -y libsqlite3-mod-spatialite
```

**Comment by DGuidi** [comment]
best way I've found to avoid to create a new test project ".net framework only" is to take the nuget file "as is" and unzip inside project folder, see https://github.com/DGuidi/NetTopologySuite.IO.SpatiaLite/commit/cc9cfd661a4448f349a3b7072f5a15b1e72f2dff

**Comment by airbreather** [comment]
> @FObermaier @airbreather I need help for this, [DGuidi/NetTopologySuite.IO.SpatiaLite@3a7e75e](https://github.com/DGuidi/NetTopologySuite.IO.SpatiaLite/commit/3a7e75e79cc817ad938a2a86a4c29d07a60cc3da) (see comments on failing tests)
> 
> Thanks for any kind of support.

Failing tests are because the WKT writer in NTS 1.x has horrible Z/M support.  Using `AsBinary` for the plain geometry comparison and hardcoding the expected WKT is enough to get those to pass.

> best way I've found to avoid to create a new test project ".net framework only" is to take the nuget file "as is" and unzip inside project folder, see [DGuidi/NetTopologySuite.IO.SpatiaLite@cc9cfd6](https://github.com/DGuidi/NetTopologySuite.IO.SpatiaLite/commit/cc9cfd661a4448f349a3b7072f5a15b1e72f2dff)

@DGuidi I figured it out thanks to @bricelam's link above.

DGuidi/NetTopologySuite.IO.SpatiaLite#1 has the fixes for everything I've said in this comment.

**Comment by airbreather** [comment]
https://www.nuget.org/packages/NetTopologySuite.IO.GeoPackage

Thanks to @DGuidi for getting the ball rolling on it.
