### ISSUE TITLE
Aggregate operations

### ISSUE THREAD

**Issue by bricelam** [NetTopologySuite/NetTopologySuite#246]
Any plans to provide a different syntax for aggregate operations? The existing APIs aren't very LINQ friendly.

Operation | Current API | Better API
--- | --- | ---
Collect | new GeometryCollection(geometries.ToArray()) | Geometry.Collect(geometries)
Envelope | new GeometryCollection(geometries.ToArray()).Envelope() | Geometry.Envelope(geometries)
Union | new GeometryCollection(geometries.ToArray()).Union() | Geometry.Union(geometries)

**Comment by airbreather** [comment]
Collect
--
We do have this, is what what you need?
```csharp
NetTopologySuite.Geometries.Utilities.GeometryCombiner.Combine(geometries)
```

...though for some reason it's `ICollection<IGeometry>` instead of `IEnumerable<IGeometry>` 😞 I think it should probably be fine to just add an overload, though.

Envelope
--
Wouldn't this work?
```csharp
geometries.Aggregate(new Envelope(), (e1, e2) => e1.ExpandedBy(e2))
```

Union
--
Same idea as with Collect:
```csharp
NetTopologySuite.Operation.Union.UnaryUnionOp.Union(geometries)
```

this one's even worse, as it takes `IList<IGeometry>` (`IEnumerable<IGeometry>` overload should be fine to add, though)

**Comment by bricelam** [comment]
Thanks! Those look better. `IEnumerable<>` overloads would be perfect.

>  ..it would probably be a nightmare to recognize all the likely variations of this pattern...

lol, yes, but I was less concerned with `Envelope` aggregate...

**Comment by airbreather** [comment]
One thing to note about `GeometryCombiner`, IIRC, it "flattens out" nested collections and returns the most specific type it can, so it's not **exactly** equivalent to `new GeometryCollection(geometries).ToArray()`.

I'll update this comment once I get home and have a chance to test this stuff, but some examples of what I recall this doing:

Combine(POLYGON, POLYGON, MULTIPOLYGON) = MULTIPOLYGON
Combine(GEOMETRYCOLLECTION(LINESTRING, LINESTRING), LINESTRING) = MULTILINESTRING
Combine(POINT, POINT, POLYGON) = GEOMETRYCOLLECTION

**Comment by airbreather** [comment]
For reference, equivalent query from my work computer which is running SQL Server 13.0.5026.0:
```sql
with t as (
  select [geometry]::STGeomFromText('POLYGON ((0 0, 1 0, 1 1, 0 1, 0 0))', 0) as g
  union all
  select [geometry]::STGeomFromText('MULTIPOLYGON (((10 10, 11 10, 11 11, 10 11, 10 10)), ((20 20, 21 20, 21 21, 20 21, 20 20)))', 0) as g
  union all
  select [geometry]::STGeomFromText('GEOMETRYCOLLECTION (POLYGON ((30 30, 31 30, 31 31, 30 31, 30 30)), POLYGON ((40 40, 41 40, 41 41, 40 41, 40 40)))', 0) as g
  union all
  select [geometry]::STGeomFromText('GEOMETRYCOLLECTION (MULTIPOLYGON (((30 30, 31 30, 31 31, 30 31, 30 30))), MULTIPOLYGON (((40 40, 41 40, 41 41, 40 41, 40 40))))', 0) as g
  union all
  select [geometry]::STGeomFromText('MULTIPOLYGON (((20 20, 21 20, 21 21, 20 21, 20 20)), ((30 30, 31 30, 31 31, 30 31, 30 30)))', 0) as g
  union all
  select [geometry]::STGeomFromText('POINT (20 20)', 0) as g
  union all
  select [geometry]::STGeomFromText('LINESTRING (20 21, 30 21)', 0) as g
  union all
  select [geometry]::STGeomFromText('MULTIPOINT ((20 20), (20 21))', 0) as g
  union all
  select [geometry]::STGeomFromText('POINT (20 20)', 0) as g
)
select ([geometry]::CollectionAggregate(t.g)).STAsText() from t;
```

manually formatted results:
```
GEOMETRYCOLLECTION (
  POLYGON ((0 0, 1 0, 1 1, 0 1, 0 0)),
  MULTIPOLYGON (((10 10, 11 10, 11 11, 10 11, 10 10)), ((20 20, 21 20, 21 21, 20 21, 20 20))),
  POLYGON ((30 30, 31 30, 31 31, 30 31, 30 30)),
  POLYGON ((40 40, 41 40, 41 41, 40 41, 40 40)),
  MULTIPOLYGON (((30 30, 31 30, 31 31, 30 31, 30 30))),
  MULTIPOLYGON (((40 40, 41 40, 41 41, 40 41, 40 40))),
  MULTIPOLYGON (((20 20, 21 20, 21 21, 20 21, 20 20)), ((30 30, 31 30, 31 31, 30 31, 30 30))),
  POINT (20 20),
  LINESTRING (20 21, 30 21),
  MULTIPOINT ((20 20), (20 21)),
  POINT (20 20)
)
```

**Comment by airbreather** [comment]
818ce13 adds `EnvelopeCombiner.Combine(geoms)`.

NetTopologySuite/GeoAPI#66 should take care of `ICollection<T>` --> `IEnumerable<T>`.

**Comment by bricelam** [comment]
I'm not sure how far you want to take this, but here are some other supported aggregate operations:

* Microsoft SQL Server
  * ✔ CollectionAggregate
  * [ConvexHullAggregate](https://docs.microsoft.com/en-us/sql/t-sql/spatial-geometry/convexhullaggregate-geometry-data-type?view=sql-server-2017)
  * ✔ EnvelopeAggregate
  * ✔ UnionAggregate
* [SpatiaLite](http://www.gaia-gis.it/gaia-sins/spatialite-sql-4.3.0.html)
  * MakeLine
  * ✔ Extent (I think this is the same as Envelope)
  * ✔ GUnion
  * ✔ Collect
  * Polygonize
* [PostGIS](https://postgis.net/docs/manual-2.5/PostGIS_Special_Functions_Index.html#PostGIS_Aggregate_Functions)
* [Oracle](https://docs.oracle.com/cd/B28359_01/appdev.111/b28400/sdo_aggr.htm#SPATL130)

**Comment by airbreather** [comment]
Convex hull aggregation seems reasonable since there's a unique result and it's just a matter of exposing what's already there.  I've done it in 715efff, but that's not yet merged to `develop` because I'm still thinking on it and I should at least split the two different things that this commit does into separate commits.

Polygonize probably makes sense too, but... it's a complicated operation, and I don't think its behavior is fully standardized.  This makes me a bit worried that if we put it in there, there could be some **significant** differences in results depending on whether it's executed client-side or server-side: I'm not 100% sure that everybody will handle dangles / cut edges / self-intersections the same way.

re: MakeLine, I don't think there's a direct equivalent in JTS, and it feels like it's of limited use, so I'm not going to jump on it right now.

`Centroid.GetCentroid(GeometryCombiner.Combine(theGeometryColumn))` feels like a match for Oracle's [SDO_AGGR_CENTROID](https://docs.oracle.com/cd/B28359_01/appdev.111/b28400/sdo_aggr.htm#SPATL1043), though I'm not sure if EF Core can detect something like this.

Nothing else on the PostGIS / Oracle links jumped out at me as something to add (if there is something, then someone could open a separate issue for it).

**Comment by airbreather** [comment]
> `Centroid.GetCentroid(GeometryCombiner.Combine(theGeometryColumn))` feels like a match for Oracle's [SDO_AGGR_CENTROID](https://docs.oracle.com/cd/B28359_01/appdev.111/b28400/sdo_aggr.htm#SPATL1043)

Not quite, actually: Oracle's version of this does something different (it doesn't specify how lines are handled, and if there are polygon-type inputs present then all point-type inputs are ignored), and I'm not sure it makes sense to expose something in NTS like that, especially not just for Oracle's sake.

**Comment by airbreather** [comment]
OK, everything I want to do with this on has been merged to `develop`:
1. Everything referenced here accepts `IEnumerable<T>`
1. `NetTopologySuite.Geometries.Utilities.EnvelopeCombiner` is a thing now
1. `NetTopologySuite.Algorithm.ConvexHull` now has a `Create` method

Latest package on MyGet includes it.

If someone needs something else specific, then they can ask for it specifically.

Closing this one.
