### ISSUE TITLE
Question: Advice on breaking changes for NtsGeometryServices

### ISSUE THREAD

**Issue by m1dst** [NetTopologySuite/NetTopologySuite#332]
Microsoft have some sample code on reprojecting geometry.  This code no longer compiles due to recent updates to NTS.   They have an open issue https://github.com/aspnet/EntityFramework.Docs/issues/1639 for the documentation which can be found at https://github.com/aspnet/EntityFramework.Docs/blob/master/entity-framework/core/modeling/spatial.md

Would you be able to advise how the simple code can be changed to support the recent changes?

**Comment by FObermaier** [comment]
Note: The matching ProjNet version is not on NuGet yet.

**Comment by FObermaier** [comment]
Sorry, it didn't make it to a [Release](https://github.com/NetTopologySuite/ProjNet4GeoAPI/releases) then.

**Comment by bricelam** [comment]
Updated in https://github.com/aspnet/EntityFramework.Docs/pull/1719. It's ugly an inefficient, but I tried to keep the code as compatible with 1.x as I could.

**Comment by IanKemp** [comment]
What is the rationale for removing GeoAPI interfaces and using concrete implementations instead? Doing so makes it very difficult for consumers to test, as they can no longer substitute their own implementations.

BTW you should probably consider updating your wiki...

**Comment by airbreather** [comment]
> What is the rationale for removing GeoAPI interfaces and using concrete implementations instead? Doing so makes it very difficult for consumers to test, as they can no longer substitute their own implementations.

To clarify, basically all the interesting functionality on `NetTopologySuite.Geometries.Geometry` itself is in virtual / abstract methods; compared to older versions, the only extra thing that you should have to do for this type is provide an instance of `GeometryFactory` to the base constructor.
- The out-of-the-box subclasses, such as `NetTopologySuite.Geometries.Polygon`, are less amenable to overriding their specific members, but I don't expect this to block anyone.

Some interesting methods aren't virtual because they're defined in terms of methods that are... e.g., `x.CoveredBy(y)` is defined as `y.Covers(x)`.

The justification stems from the fact that `NetTopologySuite.Geometries.Geometry`, like the counterpart in JTS that it came from, is **already an abstraction**.
- Adding another layer of abstraction on top of it is not just redundant, but because this other layer is an interface, it's harder for us to make non-breaking changes in the future, and it's harder for implementers to take advantage of that abstraction since they have to supply an implementation for **all** members instead of just the `abstract` ones and a subset of the `virtual` ones.
- Default interface implementations aren't coming until C# 8, and the classic .NET Framework will never get them, so we can't add members to the interface to make things easier for consumers without breaking any alternative implementations that might exist.

The discussions we had on the topic can be found across a few issues (plus unrelated discussion, sorry...):
- NetTopologySuite/GeoAPI#30
- NetTopologySuite/GeoAPI#67
- NetTopologySuite/GeoAPI#68
- NetTopologySuite/GeoAPI#70

**Comment by IanKemp** [comment]
OK, that all makes sense. Considering the breadth and breaking-ness of these changes, is it likely we'll see them in the `Microsoft.EntityFrameworkCore.SqlServer.NetTopologySuite` package when that gets bumped to 3.0 with the impending (i.e. literally today) release of .NET Core 3.0?

**Comment by airbreather** [comment]
> is it likely we'll see them in the `Microsoft.EntityFrameworkCore.SqlServer.NetTopologySuite` package when that gets bumped to 3.0 with the impending (i.e. literally today) release of .NET Core 3.0?

Yes.  We have coordinated with the EF Core team to ensure that EF Core 3.0 will use NTS 2.0.

**Comment by trevelyanuk** [comment]
This broke some things for me too; I have a custom resolver - for Automapper - that maps two doubles to a point that can be stored. 

```
public class GeometryResolver : IMemberValueResolver<HistoryModel, History, double[], IGeometry>
    {
        public IGeometry Resolve(HistoryModel model, History entity, double[] srcMember, IGeometry destMember, ResolutionContext context)
        {
            var geometryFactory = NtsGeometryServices.Instance.CreateGeometryFactory(srid: 4326);
            var coord = new GeoAPI.Geometries.Coordinate(srcMember[0], srcMember[1]);
            destMember = geometryFactory.CreatePoint(coord);
            return destMember;
        }
    }
```


Updating `Microsoft.EntityFrameworkCore.SqlServer.NetTopologySuite` to version 3.0 had the effect of breaking this line, by suggesting that it cannot convert from 'GeoAPI.Geometries.Coordinate' to 'NetTopologySuite.Geometries.Coordinate'

`destMember = geometryFactory.CreatePoint(coord);`

Eventually, I decided to change to `NetTopologySuite.Geometries.Coordinate` and then change the return type from `IGeometry` to `Geometry`, which seems like it should work. However, this then breaks Automapper, where it suggests that it "Cannot convert lambda expression to type 'string' because it is not a delegate type";

```
 cfg.CreateMap<RecordModel, Record>()
       .ForMember(dest => dest.Location, opts => opts.MapFrom<GeometryResolver, double[]>(src => (new double[] { src.devLon, src.devLat })))

```

I've reverted back to 2.2.x for now, but I'm a bit unsure as to what the issue exactly is; I've come to the conclusion that IGeometry must have been a delegate in a way that Geometry isn't, but I'm not sure where to look to confirm that (or what would need fixing)..

**Comment by airbreather** [comment]
@trevelyanuk please open a new issue for this
