### ISSUE TITLE
Coordinate as a Struct

### ISSUE THREAD

**Issue by SamuelEnglard** [NetTopologySuite/NetTopologySuite#357]
While it would be a breaking change, having `Coordinate` as a struct it would make large geometries more memory efficient. Is there any reason it is currently a class?

**Comment by airbreather** [comment]
> having `Coordinate` as a struct it would make large geometries more memory efficient.

When this starts getting relevant, I recommend using an alternative `CoordinateSequenceFactory` subclass, such as `PackedCoordinateSequenceFactory.DoubleFactory`, which stores the coordinate data more efficiently.  `Coordinate` instances would then only be allocated on an as-needed basis, and discarded at appropriate times (assuming that they're truly no longer referenced by anything you're doing).

> Is there any reason it is currently a class?

The main reason is because we inherited this design from JTS, which is written in Java, which doesn't support user-defined value types :cry:.

But another reason is that this lets subclasses add overrides to store dimensions beyond `X` and `Y`.  Some algorithms would also, perhaps, be slower by changing it to a `struct`: instead of copying pointers around, they would be copying a pair of `double` values around, which is at least twice as much data to be copying.  The cost of pointer chasing would **probably** outweigh this, but I haven't run any tests to confirm.

**Comment by SamuelEnglard** [comment]
Using `PackedCoordinateSequenceFactory.DoubleFactory` works, and the question is answered so I'm closing
