### ISSUE TITLE
Upgrading to v.2 causes various bugs with various providers. 

### ISSUE THREAD

**Issue by iashaik** [NetTopologySuite/NetTopologySuite#359]
### Description
Upgrading to v.2 have various bugs with various providers. 
1. SqlLite and Microsoft.EntityFrameworkCore.Sqlite.NetTopologySuite v 2.2.6 
**System.InvalidOperationException: No coercion operator is defined between types 'System.String' and 'NetTopologySuite.Geometries.Point'.**
2. SqlServer and Microsoft.EntityFrameworkCore.SqlServer.NetTopologySuite v2.2.6 
Fails to create database context and throws
**System.MissingMethodException: 'Method not found: 'GeoAPI.IGeometryServices NetTopologySuite.NtsGeometryServices.get_Instance()'.'** 
3. InMemory 
Fails to create database and throws 
*'The property 'CityEntity.Location' is of type 'Point' which is not supported by current database provider. Either change the property CLR type or ignore the property using the '[NotMapped]' attribute or by using 'EntityTypeBuilder.Ignore' in 'OnModelCreating'.'* 

### Steps to Reproduce
Create a table with a property "Point" in Entity Framework Core 2.2 (Code First) and attempt to do some seeding on that. 

Use GeometryFactory instead of IGeometryFactory and use GeometryFactory.CreatePoint(Coordinate) instead of new Point(long, lat) 

### System Configuration
Tell us about the environment where you are experiencing the bug:
- NetTopologySuite version: 2.0 
- Other NetTopologySuite packages and versions: Microsoft.EntityFrameworkCore.Sqlite.NetTopologySuite v 2.2.6 
Microsoft.EntityFrameworkCore.SqlServer.NetTopologySuite v2.2.6 
- Environment (Operating system, version and so on):
Windows 10, Visual Studio 2019, Entity Framework Core 2.2 
- .NET Framework version: .NET Core 2.2 

### Work around
Downgrade NetTopologySuite to 1.15.3, CreatePoint using new Point() and remove the GeometryFactory.

**Comment by airbreather** [comment]
NetTopologySuite 2.x packages (and NetTopologySuite.IO.GPX 1.x) only work with the 3.x versions of EF Core provider packages.  It will all need to be upgraded together.

**Comment by bricelam** [comment]
Added a comment on https://github.com/NuGet/Home/issues/6673 to cover this case

**Comment by iashaik** [comment]
> NetTopologySuite 2.x packages (and NetTopologySuite.IO.GPX 1.x) only work with the 3.x versions of EF Core provider packages. It will all need to be upgraded together.

Shouldn't  Entity Framework Core v3 be a dependency on that in that case?

**Comment by airbreather** [comment]
> > NetTopologySuite 2.x packages (and NetTopologySuite.IO.GPX 1.x) only work with the 3.x versions of EF Core provider packages. It will all need to be upgraded together.
> 
> Shouldn't Entity Framework Core v3 be a dependency on that in that case?

I don't understand the question.  NetTopologySuite does not depend on anything in EF Core, only the other way around, and AFAIK, EF Core 3.0's own dependencies are specified adequately.

aspnet/EntityFrameworkCore#18180, if implemented, would have made it somewhat easier for the tooling to warn you when this would have happened, but that just feels like an incomplete workaround for what I think is a much bigger problem with the ecosystem in general...

Namely, we are strongly encouraged to use SemVer for our NuGet package version numbers.  SemVer specifies that incrementing the major version is an acceptable way to communicate that a particular version of a package may not be strictly compatible with earlier versions.  However, the tooling in our ecosystem makes it **far** too easy to publish an intermediate package (such as EF Core 2.x) with a dependency on a package with major version "n" that would also be satisfied with major version "n + 1".

It turns out that I'm [not the only one](https://codeblog.jonskeet.uk/2019/10/25/options-for-nets-versioning-issues/) who feels that this is a major problem.
