### ISSUE TITLE
Can't write a shapefile with no features

### ISSUE THREAD

**Issue by JeffAtDeere** [NetTopologySuite/NetTopologySuite#36]
NTS 1.13.3.2 - I'm not sure if this is to spec or not but I am getting a NullReferenceException when writing a shape file with no features. If you uncomment the below line so that there is one feature, this works.

        public void NullReferenceWhenWriteingShapeFileWithNoFeatures()
        {
            var header = new DbaseFileHeader();
            header.AddColumn("X", 'C', 10, 0);

            var attributesTable = new AttributesTable();
            attributesTable.AddAttribute("X", "y");
            var feature = new Feature(new Point(1, 2), attributesTable);

            var writer = new ShapefileDataWriter(@"C:\temp\output") { Header = header };
            var features = new List<IFeature>();
//            features.Add(feature);
            writer.Write(features);
        }

**Comment by DGuidi** [comment]
this code looks ok with latest source code

```
DbaseFileHeader header = new DbaseFileHeader();
            header.AddColumn("X", 'C', 10, 0);
            ShapefileDataWriter writer = new ShapefileDataWriter(@"issue36") { Header = header };

            IList<IFeature> features = new List<IFeature>();
            writer.Write(features); 
```

no exception is thrown

**Comment by JeffAtDeere** [comment]
When you say latest, what version do you mean? I am using 1.13.3.2 which is the latest in nuget.

**Comment by DGuidi** [comment]
I mean source code, so maybe it's a bug fixed in latest versions.
Can you try to compile source code directly from github and verify?

**Comment by airbreather** [comment]
I can confirm that the provided code does indeed throw NullReferenceException in the latest NuGet package (1.13.3.2), and it does not throw NullReferenceException in a build from the latest source.  Stepping through, it looks like c4cca6c is where the fix was ("bounds" was null in WriteShpHeader).

Tested on Windows 8.1, x64.

**Comment by DGuidi** [comment]
Thanks for the verify

----- Messaggio originale -----
Da: "airbreather" <notifications@github.com>
Inviato: ‎28/‎04/‎2015 01:34
A: "NetTopologySuite/NetTopologySuite" <NetTopologySuite@noreply.github.com>
Cc: "Diego Guidi" <diegoguidi@gmail.com>
Oggetto: Re: [NetTopologySuite] Can't write a shapefile with no features (#36)

I can confirm that the provided code does indeed throw NullReferenceException in the latest NuGet package (1.13.3.2), and it does not throw NullReferenceException in a build from the latest source. Stepping through, it looks like c4cca6c is where the fix was ("bounds" was null in WriteShpHeader).
Tested on Windows 8.1, x64.

**Comment by JeffAtDeere** [comment]
:+1: Thank you for the verify. Given that this was fixed in December and the last patch release of NTS was in September, I hope there is a new version soon :)
