### ISSUE TITLE
Polygon Union throws exception.

### ISSUE THREAD

**Issue by juliusfriedman** [NetTopologySuite/NetTopologySuite#390]
Exception occurs in `FastNodingValidator.CheckValid`

> found non-noded intersection between LINESTRING ( -0.51137735361377157 52.023369606581014, -0.53176213899362323 52.057849844819536 ) and LINESTRING ( -0.51137735361377046 52.023369606581014, -0.58504228853285667 52.147971580970484 ) [ (-0.5243439260170377, 52.04530216546111) ]

The polygons are:

{POLYGON ((-1.0634452951380922 52.685367767956443, -0.91496739060578736 52.508098874379037, -0.80033595155707282 52.44529111136567, -0.72780097291754242 52.450727552445166, -0.6821017 52.5081058, -0.6818317 52.5081185, -0.6814398 52.5072144, -0.6802391 52.5031553, -0.6809728 52.4988933, -0.681519 52.4970216, -0.6934804 52.4744466, -0.6949555 52.4720651, -0.6963329 52.4700085, -0.6975253 52.4684368, -0.6980167 52.4678913, -0.7001403 52.4656741, -0.7046329 52.462121, -0.72476977011558352 52.449172309351106, -0.6988197869865983 52.407200889575336, -0.5307509 52.225681, -0.52937732142645266 52.223330753154812, -0.527915 52.221668, -0.4780394 52.1341366, -0.4771737 52.1322192, -0.4764504 52.1301134, -0.4762905 52.1277992, -0.47815073739638969 52.112365231109081, -0.4794075 52.0972418, -0.48090222621478756 52.095032459291218, -0.50070610848068364 52.013834733358856, -0.49995807728408659 52.011250191671607, -0.4943089 52.0031503, -0.49383101288004977 52.002359243675713, -0.36924431433427118 51.849967581694791, -0.3689542 51.849684, -0.36851108691980844 51.849070714327695, -0.3683398 51.8488612, -0.36794850896778936 51.848300381273106, -0.3677792 51.8480975, -0.35900303566862951 51.835931001921075, -0.3567661 51.8328863, -0.35642646616345008 51.832315627600394, -0.3560451 51.831732, -0.35505722188290789 51.830014944231628, -0.32626475433161012 51.781636176335773, -0.325275 51.7802131, -0.32600526300038446 51.781185503913726, -0.32505019235307125 51.778962219640995, -0.3249965 51.7795598, -0.3233541 51.7761337, -0.3230534 51.7752754, -0.32284296607032603 51.7738240746309, -0.3223155 51.7725962, -0.3212637 51.764865, -0.3210858 51.7632132, -0.3188659 51.7354772, -0.3188122 51.7326063, -0.3204024 51.7014937, -0.32050689210992234 51.700859097606561, -0.3204956 51.700596, -0.320556538953315 51.700557581964212, -0.3207876 51.6991543, -0.32318204730346278 51.699507174545559, -0.3246368 51.6990948, -0.32490363161928587 51.6997946569901, -0.3265663 51.7000961, -0.3627730118872397 51.821235011760308, -0.41768713825638537 51.873711880271038, -0.4907233 51.9250657, -0.4920899 51.9261369, -0.4929232 51.9270335, -0.4939036 51.9281635, -0.4946357 51.9291511, -0.4956718 51.9309758, -0.4958849 51.9316019, -0.4963376 51.9336702, -0.50239778441962446 51.997001791089787, -0.51137735361377123 52.023369606581014, -0.51137735361377157 52.023369606581014, -0.53176213899362323 52.057849844819536, -0.67686552497281227 52.303287764549786, -0.80601925317045953 52.441785972539265, -0.8223058714176813 52.445094541142858, -0.8247256 52.4454596, -0.82482965480436488 52.44549233967485, -0.8248882 52.4454973, -0.8685905 52.4556439, -0.9041596 52.4698465, -0.9051987 52.4703493, -0.906048 52.4708702, -0.906369924725132 52.471149000572126, -1.1098389 52.5717772, -1.1111698 52.5724696, -1.1140844 52.5740524, -1.1157225 52.5749804, -1.116478224907238 52.575448244229385, -1.116824 52.5756451, -1.1168996952239243 52.575709162526017, -1.1169613 52.5757473, -1.1182794 52.576712, -1.1241808 52.5817813, -1.1261214 52.5837125, -1.1385583 52.616502, -1.1312585441484226 52.630329362976141, -1.1372681 52.7473875, -1.1370934 52.7474417, -1.127987 52.7478879, -1.017847785083313 52.739427661734943, -0.99832552392104612 52.748884442801256, -0.9981354 52.7490153, -0.99755710663459563 52.749256671918829, -0.9971161 52.7494703, -0.9967951 52.7496205, -0.995115 52.7503827, -0.9933391 52.750938, -0.993145166577293 52.750982048336944, -0.9915384 52.7515745, -0.9654348 52.7559708, -0.963943502050885 52.756184691490112, -0.9639435020508238 52.75618469149012, -0.9631362 52.7563215, -0.9627239559412939 52.756365140524991, -0.9619713 52.7564952, -0.96158535463738337 52.756522912074729, -0.9614948 52.7565359, -0.9599658 52.7566779, -0.95929073982020985 52.756728583856095, -0.9590242 52.7567568, -0.95887314142101721 52.756759937352868, -0.8816432 52.7625584, -0.87234305896644815 52.761862496879552, -0.7965499 52.7649408, -0.79634224454476943 52.7649173013797, -0.7961815 52.7649081, -0.7933734 52.764676, -0.79276536628361161 52.764512536168823, -0.7908439 52.7642951, -0.79164634453830973 52.764211698276576, -0.7868859 52.7629319, -0.7851425 52.7621358, -0.78448839983014473 52.7617631428599, -0.7845835 52.7618795, -0.78431403963605562 52.761663805519426, -0.7834487 52.7611708, -0.7831329 52.7609159, -0.7816963 52.7597018, -0.78056925546482747 52.758666224484273, -0.73048529393452355 52.718575600730325, -0.7289189 52.7174244, -0.7251722 52.7135167, -0.723687 52.7109525, -0.7230204 52.709376, -0.7218379 52.7060344, -0.6972471 52.6279637, -0.7052893 52.6366937, -0.7323186 52.6665711, -0.7345554 52.6694665, -0.7355839 52.6726094, -0.74969252948984866 52.73172392214164, -0.7524542 52.7337027, -0.75802893421180251 52.737708456014175, -0.8277233 52.760075, -0.82662809479753441 52.760575885306643, -0.8317023 52.7600485, -0.842903 52.7596569, -0.84539499092801729 52.75975131837648, -0.98594987930791123 52.74532922469583, -1.016474180248599 52.734248625925396, -1.0634452951380922 52.685367767956443))}

And

{POLYGON ((-0.48090222621478756 52.095032459291218, -0.5014521 52.0107761, -0.5073182 52.0166926, -0.5089374 52.0192425, -0.6785603270754752 52.306154470241218, -0.7766709 52.4408784, -0.7329858 52.4441013, -0.5307509 52.225681, -0.52937732142645266 52.223330753154812, -0.527915 52.221668, -0.4780394 52.1341366, -0.4771737 52.1322192, -0.4764504 52.1301134, -0.4762905 52.1277992, -0.47815073739638969 52.112365231109081, -0.4794075 52.0972418, -0.48090222621478756 52.095032459291218))}

Also noting that when I first call `ConvexHull` and then `Union` this doesn't occur

**Comment by juliusfriedman** [comment]
Another example:

> {POLYGON ((-0.8248882 52.4454973, -0.9172001 52.5092685, -0.9202506 52.5109936, -0.9353859 52.5188364, -0.9445768 52.5235346, -0.9581483 52.5304255, -0.9876509 52.5373124, -0.995498 52.5388914, -1.0049348 52.5405561, -0.906048 52.4708702, -0.9051987 52.4703493, -0.9041596 52.4698465, -0.8685905 52.4556439, -0.8248882 52.4454973))}

And

> {POLYGON ((-0.8248882 52.4454973, -0.9172001 52.5092685, -0.9202506 52.5109936, -0.9353859 52.5188364, -0.9445768 52.5235346, -0.9581483 52.5304255, -0.9876509 52.5373124, -0.995498 52.5388914, -1.0049348 52.5405561, -0.906048 52.4708702, -0.9051987 52.4703493, -0.9041596 52.4698465, -0.8685905 52.4556439, -0.8248882 52.4454973))}

**Comment by airbreather** [comment]
Known issue that we inherited from JTS.

From https://locationtech.github.io/jts/jts-faq.html#D1 (emphasis mine):
> Unfortunately there is no guaranteed way of avoiding TopologyExceptions. **However, a heuristic which often helps is to ensure that input geometry coordinates do not carry excessive precision. Instead of providing coordinates with a full 16 digits of precision (which usually far exceeds the actual accuracy of the input data), try reducing precision to a few decimal places.** Of course, correct geometry topology must still be maintained. (This is primarily an issue for polygons, and can be tricky to do in some pathological cases). JTS provides the SimpleGeometryPrecisionReducer class to do a simple reduction in coordinate precision, although this class is not guaranteed to maintain correct geometry topology.

**Comment by juliusfriedman** [comment]
Just curious whats the best way to work around this if any? try/catch and then reduce?

What is strange to me is that I have had success by calling `ConvexHull` first and then performing the `Union` on that. Can you briefly explain why that works also?

**Comment by airbreather** [comment]
> What is strange to me is that I have had success by calling `ConvexHull` first and then performing the `Union` on that. Can you briefly explain why that works also?

It "works" because the issue happens at a point well within the convex hull of both polygons, so the whole issue just gets deleted.  You wind up taking the union of these:
![image](https://user-images.githubusercontent.com/3792815/76462140-8f25b700-63b7-11ea-94c1-0af001576983.png)

and the closest you ever get to an intersection is **well** within the outer one:
![image](https://user-images.githubusercontent.com/3792815/76462199-a664a480-63b7-11ea-8c8b-897bc3f72906.png)

So the union of the convex hulls just winds up being the convex hull of the first polygon.

The first polygon (overlaid with the second) looks like this, with vertices of the first polygon highlighted:
![image](https://user-images.githubusercontent.com/3792815/76460317-2a1c9200-63b4-11ea-8798-51f570fbaabb.png)

Note that the first polygon has an edge that appears to run right along an edge of the second polygon.  However, if I zoom in **maddeningly close** to it, that's not the case:
![image](https://user-images.githubusercontent.com/3792815/76460446-65b75c00-63b4-11ea-9cc4-158374d4fc91.png)
![image](https://user-images.githubusercontent.com/3792815/76460598-ab742480-63b4-11ea-8803-edb4289447e1.png)

That edge from the first polygon has one vertex that's just **barely** outside of the second polygon (seriously, **maddeningly** close), and one vertex that's just **barely** inside of the second polygon.  So this edge intersects the second polygon at some extremely precise location.

The area reported by the exception message is even stranger.  It's at the bottom end of that polygon.  Again, zooming in **maddeningly** close reveals:
![image](https://user-images.githubusercontent.com/3792815/76460833-263d3f80-63b5-11ea-90ac-026c139e45ea.png)

To give you an idea of how **maddeningly close** I had to zoom in to see this, the intersection point on this last image (the point where red turns into green) is less than 0.00000000000001 units away from one of the vertices in the viewport, yet the size of the polygon is a lot bigger than that.  The math behind all this just isn't designed to handle polygons that are this many orders of magnitude larger than the precision of important events such as segment intersections.

> Just curious whats the best way to work around this if any? try/catch and then reduce?
> It seems like something like [`SimpleGeometryPrecisionReducer`] is what I should use? but I am not sure WHEN I should use it, e.g. wait for the exception and then reduce?

The go-to advice that I have for this kind of situation is to try to avoid working with polygons that are specified to such a high degree of precision relative to their actual size in the first place, and that you would have to know the entire context of the failing method calls in order to be able to find the best place to implement that (typically, it will involve a pre-processing step that removes excess precision from the authoritative data source's polygons).

The primary use cases for NTS / JTS are real-world geographic areas where even the most precise specialized surveying equipment can only go about 8 places to the right of the decimal point.

**Comment by juliusfriedman** [comment]
Thanks for your detailed explanation and quick response. You may close this issue if you see fit as I have worked around it using the ConvexHull as well as some area calculations.
