### ISSUE TITLE
RFC: Delegate computation of geometry predicates, operations and properties to factory

### ISSUE THREAD

**Issue by FObermaier** [NetTopologySuite/NetTopologySuite#453]
With https://github.com/locationtech/jts/commit/31cb7b640a8b9552b912a6ac96a6e5795b6c0957 delegated computation of  Geometry overlay functions to a special class (`GeometryOverlay`). That class controls which algorithm to use by evaluating a system property.

In regard to #447 and the multiple compaints abount distance and area computations in EF context, we should consider to take another approach and delegate these operations to the GeometryFactory.

I started with a PR:
https://github.com/NetTopologySuite/NetTopologySuite/pull/452

**Comment by airbreather** [comment]
I'd prefer not to expose a `GeometryOverlay` publicly on the `GeometryFactory`; I'd prefer to have it be a separate constructor parameter on the geometry classes.  Something like:
```csharp
public class GeometryFactory
{
    private readonly GeometryOverlay _geometryOverlay;

    /* ... */

    public virtual Polygon CreatePolygon(LinearRing shell, LinearRing[] holes)
    {
        return new Polygon(shell, holes, this, _geometryOverlay);
    }
}
```

I also prefer not having a settable static `GeometryOverlay.Default`; if we need a default instance somewhere, then worst-case we could grab it from `NtsGeometryServices.Instance.GeometryOverlay` instead of having two places that mean the same thing... but I think in all cases there should be a more specific `GeometryOverlay` instance we can grab from the `Geometry` itself.

Together, these ensure that the single user-visible entry point is in setting their `NtsGeometryServices`'s `GeometryOverlay`.

I also think that, if we're going to be allowing different instances of `Geometry` to have different implementations of `GeometryOverlay` in the same application, then we ought to define rules for how to deal with cases where the user tries to mix geometries... it would be really annoying if `a.Union(b)` and `b.Union(a)` were allowed to do meaningfully different things.

- Suggestion is to have `a.Union(b)` throw an exception if `!Equals(a.GeometryOverlay, b.GeometryOverlay)`, directing them to resolve the ambiguity for us by choosing `a.GeometryOverlay.Union(a, b)` or `b.GeometryOverlay.Union(a, b)`.

I'll have more specific feedback on the PR when I get the chance to look over it in more detail.

**Comment by FObermaier** [comment]
Notes:
* I object to adding `GeometryOverlay` as a member to `Geometry`.
* I don't like to add additional constructors to `GeometryFactory` that allow for setting `GeometryOverlay`. The way it is coded setting GeometryOverlay is only possible as long as no functionality involving `GeometryOverlay` has been processed or GeometryOverlay has been set externally. At least that is the idea.

**Comment by airbreather** [comment]
> I object to adding `GeometryOverlay` as a member to `Geometry`.

Well, it's going to be there either way: I don't see a fundamental difference between `someGeometry.Factory.GeometryOverlay` and `someGeometry.GeometryOverlay`.  Making it a first-class member of the factory itself just perpetuates this weird pattern where we have random properties like `SRID` and `PrecisionModel` that aren't actually used when creating geometries, despite this class being called "`GeometryFactory`".

> I suppose we tend to have more geometries than factories, so that is not an option.

If this statement was meant to refer to the number of geometry *classes* that would need constructor overloads to let this work, then yeah, I agree, that's annoying.  It's one of the major reasons why external callers should **strongly** favor using `GeometryFactory` methods for creating their instances, and why I think it was a mistake to make the geometry constructors `public`: if they were `internal`, then we could easily add as many parameters as we wanted without meaningfully breaking anyone.

As-is, we could still create `internal` constructors for this and any future ones, and mark the `public` ones `[Obsolete]`...

I'm not going to fight the "`Geometry` vs. `GeometryFactory`" point **too** much harder than this, since the main downside is just that we expose more non-"factory" properties on a "factory" class.

> I don't like to add additional constructors to `GeometryFactory` that allow for setting `GeometryOverlay`. The way it is coded setting GeometryOverlay is only possible as long as no functionality involving `GeometryOverlay` has been processed or GeometryOverlay has been set externally. At least that is the idea. Same for `NtsGeometryServices`.

Compared to making it immutable after the instance is created, defaulting to the current behavior for pre-existing constructors, the differences that I see between that approach and this one are:

1. We have to do something weird (or at least different) with `NtsGeometryServices`, since its `m_factories` is only correct in all cases if the instances that get passed from `NtsGeometryServices` to the `GeometryFactory` are read-only after the factory is created (which they all currently are).
1. It creates a situation where someone can set the property value on an instance and then affect the behavior of instances far away from it, perhaps developed at different times.
    - For example, as a project evolves, someone could start setting the property value when initializing their only method that uses overlay functionality, and then everything would work just fine.  Then, when they develop another method that uses overlay functionality, they set it there too, and it also works just fine... until both methods are called within the same application instance, and it starts breaking for some reason.
    - This kind of delayed feedback is the opposite of "falling into the pit of success", which suggests to me that this is an anti-pattern that we should only use sparingly.
1. It adds mutable state to types that were previously (more-or-less...) immutable.  Many developers, including myself and some of my colleagues at work, strongly prefer working with immutable objects over mutable ones as a rule, for several reasons.
    - One of the main reasons, for me, is that it reduces cognitive overhead when accepting an instance:
        - OK, I got this instance, which has these properties that I'm legally allowed to set.
            - Do I have to worry about someone else setting them while I work with it?
            - Am I expected to set them myself?
            - Am I even *allowed* to set them myself, or are these only settable so that someone else would have a slightly easier time creating the instance?
        - Removing the setter removes some of that cognitive overhead, and making the instance immutable removes all of it.
    - Another reason is that it tends to have fewer issues when dealing with instances that can be observed from multiple threads.  As-written in the PR, I think there's likely a sequence of statements that can be interleaved in a certain order to get multiple consumers to see different values for `NtsGeometryServices.GeometryOverlay` on the same instance of the `NtsGeometryServices` class, without any exceptions being thrown.  I'm not 100% sure, I haven't fully checked
1. Understood, the "set-once-at-any-time" pattern requires us to develop fewer constructors, but since it's so easy to just make some more constructors that do nothing more than set fields / call other constructors with default values, it's a really small consideration (to me).  Having said that, it is one of the (small) reasons why I didn't want to put it onto `GeometryFactory`: that class already has a ton of constructors that call other ones, passing in default values, and this may start exploding that a little bit.

**Comment by FObermaier** [comment]
> If this statement was meant to refer to the number of geometry classes that would need constructor overloads to let this work, then yeah, I agree, that's annoying.

No, this is referring to the number of instances. `GeometryOverlay` may only be the starting point. A suggestion to solve #447 included allowing to set the (Coordinate)EqualityComparer. If we then decide to allow for other distance/area computation operation classes (lat/lon with meters) we have 4 references to other classes on Geometry. For Polygon and Multi-geometries that even multiplies. I don't think that it is in any way useful and wastes space. These are all settings that are not likely to change within an application so why not unite them on the class that is already present.

**Comment by airbreather** [comment]
> No, this is referring to the number of instances. `GeometryOverlay` may only be the starting point.

OK, that makes sense.  My main remaining concern is with what we expose publicly.  I'm OK with **storing** the value on `GeometryFactory` internally, for this reason, but I'd still prefer if the only public way to **access** it, for a given `Geometry` instance, is through a property on the `Geometry` instance itself, since it still doesn't actually have anything to do with the "factory" parts of `GeometryFactory`, i.e.,
```csharp
public class GeometryFactory
{
    /* ... */

    internal GeometryOverlay GeometryOverlay { get; }

    /* ... */
}

public abstract class Geometry
{
    /* ... */

    public GeometryOverlay GeometryOverlay => Factory.GeometryOverlay;

    /* ... */
}
```

**Comment by FObermaier** [comment]
I agree on the visibility, why do we need to expose it on Geometry?

**Comment by airbreather** [comment]
> why do we need to expose it on Geometry?

Actually, I hope we don't.

My remarks mainly came from a perspective of what was already `public` in the PR and how it could have been used.  I identified at least one reason why **we** might want to know the `GeometryOverlay` instance to use for a given `Geometry` (namely, to make sure that we throw from `a.Union(b)` if it would have otherwise used a different instance than `b.Union(a)`), so I figured that there **might** be a reason for someone to use it externally, so I wanted to make sure that that was accounted for in my response.
