### ISSUE TITLE
The NetTopologySuit library gives very different results compared to the SqlGeography library

### ISSUE THREAD

**Issue by q-bertsuit** [NetTopologySuite/NetTopologySuite#669]
I'm seeing a very big difference in the results when running Intersects on a line and a polygon when compared to the Microsoft.SqlServer.Types library

I'm on version 2.5.0 of NetTopologySuit

I've posted a question about an issue on StackOverflow

https://stackoverflow.com/questions/75395966/the-nettopologysuit-library-gives-very-different-results-compared-to-the-sqlgeog

**Comment by FObermaier** [comment]
The problem is that NetTopologySuite only performs planar 2d geometry operations. 

SqlServer's `geography` type performs geodesic operations within computation of distances and/or other spatial operations.   

If you use SqlServer's `geometry` type you should be getting -more or less- the same results.
