### ISSUE TITLE
NetTopologySuite dll not digitally signed.

### ISSUE THREAD

**Issue by stefansalanta** [NetTopologySuite/NetTopologySuite#691]
The dll in the latest version of NetTopologySuite nuget is not digitally signed.

![MetTopologySuiteDll](https://github.com/NetTopologySuite/NetTopologySuite/assets/134377561/7b91976d-cca9-4485-8ce3-369e89cba9d1)

![NetTopologySuiteVersion](https://github.com/NetTopologySuite/NetTopologySuite/assets/134377561/7a6db661-8e33-47fc-9da9-f14ae3672083)

This constitutes a security risk.

Could you please sign the dll?

Thank you!

**Comment by FObermaier** [comment]
I admit that I'm not keen on investing money into this.

**Comment by bricelam** [comment]
> This constitutes a security risk.

I disagree with this statement. I think providing a SHA hash would be just as effective. NuGet also provides ways of ensuring you get it from a trusted source.

**Comment by bricelam** [comment]
Note, I've seen some companies that require this build and sign the binaries themselves.

**Comment by airbreather** [comment]
The financial issue is a problem, and I see absolutely no practical security benefit to users relative to the status quo.

See https://github.com/NetTopologySuite/NetTopologySuite.IO.GeoJSON/issues/138#issuecomment-1948301578 for some links that show how you might be able to sign the binaries on your own, in case the reason why you're asking for this is to satisfy some auditing tool's rule that you cannot otherwise suppress.
